
function(EXTRACT ARCHIVE DIRECTORY)
  file(MAKE_DIRECTORY ${DIRECTORY})
  execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf ${ARCHIVE}
    WORKING_DIRECTORY ${DIRECTORY})
endfunction(EXTRACT ARCHIVE DIRECTORY)
